# Site/SEO settings
email: ayruos@gmail.com
baseurl: ""
permalink: :title/
google_analytics: UA-26210655-1

name: Sourya Sen
title: Sourya Sen
description: >
  Personal and portfolio website of Sourya Sen.
url: http://ayruos.com
twitter_username: ayruos
default_img: /assets/images/img-contact.jpg
social:
  - name: twitter
    url: https://twitter.com/ayruos
  - name: instagram
    url: https://www.instagram.com/ayruos/
  - name: github
    url: https://github.com/sourya-sen
  - name: youtube
    url: https://www.youtube.com/channel/UCI_MuA7Gxot2FG4NlSPjXDg
  - name: bandcamp
    url: https://souryas.bandcamp.com


# Contact settings
#contact_img: /assets/images/img-contact.jpg
#formcarry: https://formcarry.com/s/noD6i_0pkZ

# Disqus settings
#disqus: test-apkdzgmqhj

# MailChimp settings
#mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
#mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

#mailchimp_action: https://gmail.us4.list-manage.com/subscribe/post-json?u=0eda558109a704ce55cef6303&amp;id=0e8e938421
#mailchimp_input: b_0eda558109a704ce55cef6303_0e8e938421

# Author settings
author:
  - name: Sourya Sen
    bio: Audiovisual Artist / Creative Technologist / Video Post Production
    url: http://ayruos.com

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts:
      - 'tag.html'
    title: 'Sourya Sen'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true


# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-compress-images
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md

iis_slider_array: []

# Compress Images
imageoptim:
  svgo: false

compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"
